openapi: 3.2.0
info:
  title: Gala Block Explorer API
  description: ''
  version: 3.0.8
  contact: {}
servers: []
tags:
- name: Explorer
paths:
  /v1/explorer/all-balances:
    get:
      operationId: ExplorerController_getBalances
      parameters:
      - name: additionalKey
        required: true
        in: query
        schema: {}
      - name: type
        required: true
        in: query
        schema: {}
      - name: category
        required: true
        in: query
        schema: {}
      - name: collection
        required: true
        in: query
        schema: {}
      - name: channel
        required: true
        in: query
        schema: {}
      responses:
        '200':
          description: ''
      tags:
      - Explorer
      summary: Explorer controller get balances
      x-summary-source: derived
  /v1/explorer/all-allowances:
    get:
      operationId: ExplorerController_getAllowances
      parameters:
      - name: additionalKey
        required: true
        in: query
        schema: {}
      - name: type
        required: true
        in: query
        schema: {}
      - name: category
        required: true
        in: query
        schema: {}
      - name: collection
        required: true
        in: query
        schema: {}
      - name: channel
        required: true
        in: query
        schema: {}
      responses:
        '200':
          description: ''
      tags:
      - Explorer
      summary: Explorer controller get allowances
      x-summary-source: derived
  /v1/explorer/bridge-ops:
    get:
      operationId: ExplorerController_getBridgeOps
      parameters:
      - name: from
        required: true
        in: query
        schema: {}
      responses:
        '200':
          description: ''
      tags:
      - Explorer
      summary: Explorer controller get bridge ops
      x-summary-source: derived
  /v1/explorer/blocks:
    get:
      operationId: CachedExplorerController_getBlocks
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      - name: offset
        required: false
        in: query
        schema:
          default: 0
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlocksResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get blocks
      x-summary-source: derived
  /v1/explorer/blocks/latest:
    get:
      operationId: CachedExplorerController_getRecentBlocks
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlindBlocksResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get recent blocks
      x-summary-source: derived
  /v1/explorer/blocks/{channel}:
    get:
      operationId: CachedExplorerController_getBlocksByChannel
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      - name: offset
        required: false
        in: query
        schema:
          default: 0
          type: number
      - name: channel
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlocksResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get blocks by channel
      x-summary-source: derived
  /v1/explorer/blocks/{channel}/latest:
    get:
      operationId: CachedExplorerController_getRecentBlocksByChannel
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      - name: channel
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlindBlocksResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get recent blocks by channel
      x-summary-source: derived
  /v1/explorer/blocks/{channel}/{number}:
    get:
      operationId: CachedExplorerController_getBlockByNumber
      parameters:
      - name: channel
        required: true
        in: path
        schema:
          type: string
      - name: number
        required: true
        in: path
        schema:
          minimum: 1
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags:
      - Explorer
      summary: Cached explorer controller get block by number
      x-summary-source: derived
  /v1/explorer/height/{channel}:
    get:
      operationId: CachedExplorerController_getBlockHeightOnChannel
      parameters:
      - name: channel
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelHeightResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get block height on channel
      x-summary-source: derived
  /v1/explorer/transactions:
    get:
      operationId: CachedExplorerController_getTransactions
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      - name: offset
        required: false
        in: query
        schema:
          default: 0
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsPagingResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get transactions
      x-summary-source: derived
  /v1/explorer/transactions/latest:
    get:
      operationId: CachedExplorerController_getRecentTransactions
      parameters:
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get recent transactions
      x-summary-source: derived
  /v1/explorer/transactions/{channel}:
    get:
      operationId: CachedExplorerController_getTransactionsByChannel
      parameters:
      - name: channel
        required: true
        in: path
        schema:
          type: string
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      - name: offset
        required: false
        in: query
        schema:
          default: 0
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsPagingResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get transactions by channel
      x-summary-source: derived
  /v1/explorer/transactions/{channel}/latest:
    get:
      operationId: CachedExplorerController_getRecentTransactionsByChannel
      parameters:
      - name: channel
        required: true
        in: path
        schema:
          type: string
      - name: limit
        required: false
        in: query
        schema:
          default: 20
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get recent transactions by channel
      x-summary-source: derived
  /v1/explorer/token-media:
    post:
      operationId: CachedExplorerController_getTokenMedia
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenListDTO'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TokenClassImageDTO'
      tags:
      - Explorer
      summary: Cached explorer controller get token media
      x-summary-source: derived
  /v1/explorer/channels:
    get:
      operationId: CachedExplorerController_getRegisteredChannels
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
      - Explorer
      summary: Cached explorer controller get registered channels
      x-summary-source: derived
  /v1/explorer/search:
    post:
      operationId: CachedExplorerController_search
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequestDTO'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponseDTO'
      tags:
      - Explorer
      summary: Cached explorer controller search
      x-summary-source: derived
components:
  schemas:
    SearchResponseDTO:
      type: object
      properties:
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/BlockDetailsDTO'
        search:
          type: object
        paging:
          $ref: '#/components/schemas/PagingResponseDTO'
      required:
      - blocks
      - search
      - paging
    SearchRequestDTO:
      type: object
      properties:
        limit:
          type: object
          default: 20
        offset:
          type: object
          default: 0
        deepSearch:
          type: object
          default: false
        search:
          type: string
      required:
      - search
    TransactionsResponseDTO:
      type: object
      properties:
        transactions:
          type: array
          items:
            type: object
      required:
      - transactions
    TokenListDTO:
      type: object
      properties:
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/TokenMediaRequestDTO'
      required:
      - tokens
    BlindBlocksResponseDTO:
      type: object
      properties:
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/BlockDetailsDTO'
      required:
      - blocks
    TokenClassImageDTO:
      type: object
      properties:
        image:
          type: string
        collection:
          type: string
        category:
          type: string
        type:
          type: string
        additionalKey:
          type: string
      required:
      - image
      - collection
      - category
      - type
      - additionalKey
    BlocksResponseDTO:
      type: object
      properties:
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/BlockDetailsDTO'
        paging:
          $ref: '#/components/schemas/PagingResponseDTO'
      required:
      - blocks
    PagingResponseDTO:
      type: object
      properties:
        limit:
          type: number
        offset:
          type: number
        size:
          type: number
        count:
          type: string
      required:
      - limit
      - size
      - count
    TransactionsPagingResponseDTO:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingResponseDTO'
        transactions:
          type: array
          items:
            type: object
      required:
      - paging
      - transactions
    TokenMediaRequestDTO:
      type: object
      properties:
        collection:
          type: string
        category:
          type: string
        type:
          type: string
        additionalKey:
          type: string
      required:
      - collection
      - category
      - type
      - additionalKey
    ChannelHeightResponseDTO:
      type: object
      properties:
        height:
          type: string
      required:
      - height
    BlockDetailsDTO:
      type: object
      properties:
        block:
          type: object
        channel:
          type: string
        number:
          type: string
        parsedBlock:
          type: object
      required:
      - block
      - channel
      - number
      - parsedBlock
